apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: argodemo-rollout
  namespace: default
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argodemo
  template:
    metadata:
      labels:
        app: argodemo
    spec:
      containers:
      - name: demo
        image: argoproj/rollouts-demo:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
